"""removed icon from folders

Revision ID: 6bf691ce892a
Revises: 96e9f20dadd8
Create Date: 2025-02-20 23:33:36.255125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf691ce892a'
down_revision: Union[str, None] = '96e9f20dadd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_column('folders', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('icon', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('files', 'name')
    # ### end Alembic commands ###
