"""Removed access token.

Revision ID: 6e0f8c720536
Revises: fbe53a38d875
Create Date: 2025-02-04 01:36:52.605468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0f8c720536'
down_revision: Union[str, None] = 'fbe53a38d875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
