"""removed transcript table

Revision ID: 7a447703095c
Revises: d469e1f6b6d1
Create Date: 2025-03-03 19:18:21.223946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a447703095c'
down_revision: Union[str, None] = 'd469e1f6b6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcripts')
    op.add_column('notes', sa.Column('transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'transcript')
    op.create_table('transcripts',
    sa.Column('id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('note_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name='transcripts_note_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transcripts_pkey')
    )
    # ### end Alembic commands ###
