"""changed File Model for content.

Revision ID: 9609fa9a5d5c
Revises: 5496e1ba2fe4
Create Date: 2025-02-10 18:39:10.084222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9609fa9a5d5c'
down_revision: Union[str, None] = '5496e1ba2fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('files', 'content_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('content_link', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('files', 'content')
    # ### end Alembic commands ###
