"""Updated subscription table

Revision ID: 9cf2428eaa35
Revises: 4b4da5912cf2
Create Date: 2025-03-08 15:32:16.672318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cf2428eaa35'
down_revision: Union[str, None] = '4b4da5912cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('razorpay_id', sa.String(length=255), nullable=False))
    op.add_column('subscriptions', sa.Column('plan_id', sa.String(length=255), nullable=False))
    op.add_column('subscriptions', sa.Column('status', sa.String(), nullable=False))
    op.add_column('subscriptions', sa.Column('next_billed_date', sa.DateTime(), nullable=False))
    op.add_column('subscriptions', sa.Column('cancelled_at', sa.DateTime(), nullable=False))
    op.drop_column('subscriptions', 'stripe_id')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('stripe_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'cancelled_at')
    op.drop_column('subscriptions', 'next_billed_date')
    op.drop_column('subscriptions', 'status')
    op.drop_column('subscriptions', 'plan_id')
    op.drop_column('subscriptions', 'razorpay_id')
    # ### end Alembic commands ###
