"""added video id in file models

Revision ID: d469e1f6b6d1
Revises: 6bf691ce892a
Create Date: 2025-02-26 20:16:41.277030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd469e1f6b6d1'
down_revision: Union[str, None] = '6bf691ce892a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('video_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'video_id')
    # ### end Alembic commands ###
